### ISSUE TITLE
Support developer telemetry via Plugin API v1

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#21]
## Context

Old context, from edX: _The edX Arch team has invested time in implementing Devstack metrics, with the intention of rolling most of that effort into the Tutor system. Current metrics enable us to understand which Devstack commands are used and how long each of them take._

We would like to avoid adding telemetry to Tutor itself. However, the a plugin against the Tutor API v1 should be capable of collecting data and exporting it.

## Acceptance

The v1 Plugin API should provide hooks for 2U to implement some sort of developer experience tracking mechanism if that's something they still want to do.

**Comment by regisb** [comment]
I strong dislike all uses of telemetry, especially in open source products. So I would very much like to avoid adding telemetry to tutor itself. Measuring user engagement should be possible by creating a dedicated plugin that will parse `sys.argv` and report to some backend -- but I'd rather not be the one to implement that...

**Comment by kdmccormick** [comment]
I agree. I would not want to be the one to implement this either. I am inclined to close this issue (it's from a while ago).

If a request for telemetry comes in again from a stakeholder, perhaps then we point them to the plugin API so that they could build a tracking plugin for their own employees to install.

@regisb for my enrichment, does the current plugin API provide a way to intercept every `tutor ...` command invocation? I thought they were limited to handling `tutor <plugin_name> ...`. Are you thinking they'd just `import tutor.cli` and monkey-patch from there?

**Comment by kdmccormick** [comment]
Blocked by the Plugin API v1 TEP, tracked here: https://github.com/overhangio/2u-tutor-adoption/issues/32.

**Comment by kdmccormick** [comment]
The hooks framework, as proposed in https://github.com/overhangio/tutor/pulls/599, would certainly lend itself towards a telemetry plugin. Additional Actions would need to be exposed by the Plugins V1 API, such as `SERVICE_STARTED`, `SERVICE_STOPPED`, `IMAGES_PULLED`, etc.

**Comment by kdmccormick** [comment]
Gonna close this. If 2U would like to implement telemetry, and the existing hooks weren't sufficient, then they could propose additional hooks.
