### ISSUE TITLE
Stop 'local' containers when starting 'dev' containers and vice versa

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#27]
## Context

`tutor local ...` commands start one set of containers. `tutor dev ...` starts a different set. If someone tries to run both at the same time, they will find that one's ports conflict with the other's.

Because there is no `tutor dev quickstart` command, first time developers always need to:
* first, provision with `tutor local quickstart`, then
* stop local containers with `tutor local stop`, and
* finally start dev containers with `tutor tutor dev start`.

The [Tutor dev docs](https://docs.tutor.overhang.io/dev.html#open-edx-development) do call this out:
> Once the local platform has been configured, you should stop it so that it does not interfere with the development environment:
>
>      tutor local stop

but I worry that this will be an easily overlooked stumbling block for new users. I certainly messed this up the first time :P  

Do we think that others would find this confusing too? Could we remove/mitigate this stumbling block by:
* adding a `tutor dev quickstart` that spins up dev-mode containers, or
* failing fast and loudly if one tries to start `local`/`dev` containers while the other set is already up?

## Acceptance

Referencing @regisb's comment below:

* Run `tutor dev stop` as part of `tutor local start`, and to run `tutor local stop` as part of `tutor dev start`.
* ~Introduce `tutor dev quickstart`, analogous to `tutor local quickstart`. Update the docs.~
  * This has been split off to https://github.com/overhangio/2u-tutor-adoption/issues/58

**Comment by regisb** [comment]
> but I worry that this will be an easily overlooked stumbling block for new users. I certainly messed this up the first time :P

I also keep making that mistake :sweat_smile: 

> adding a tutor dev quickstart that spins up dev-mode containers

Yes, we should do that.

> failing fast and loudly if one tries to start local/dev containers while the other set is already up?

I think that a better approach would be to run `tutor dev stop` as part of `tutor local start`, and to run `tutor local stop` as part of `tutor dev start`. This is compatible with the first item above, which is that we need to add a `dev quickstart` command.

**Comment by kdmccormick** [comment]
I had started poking at this in https://github.com/kdmccormick/tutor/pull/3, but, as Régis and I had talked about, it'd be way easier to just implement this on top of the V1 Plugins branch.

**Comment by kdmccormick** [comment]
Blocked by #32

**Comment by kdmccormick** [comment]
Will be Resolved by https://github.com/overhangio/tutor/pull/646
