### ISSUE TITLE
Clarify plugin development docs a bit

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#30]
## Context

Some clarifications I wrote while working on a plugin: https://github.com/overhangio/tutor/pull/564

Update: opened a new PR with the same changeset, here: https://github.com/overhangio/tutor/pull/588

## Acceptance

Polish the PR. (@kdmccormick  - done)
Reopen it for review, or decide to keep it closed (@regisb)

**Comment by regisb** [comment]
Should I re-open that PR? Or should we wait to create a full-fledged "plugin developer guide", as I suggested in #29?

**Comment by kdmccormick** [comment]
@regisb I had originally planned to add more suggestions to that docs PR, but given the upcoming Plugin V1 API and your plugin developer guide idea, I'm going to stop adding to it.

That being said, I just rebased it and looked back through my suggested changes. It's ready for review and I think it the PR could be valuable for developers on the V0 Plugin API. At your discretion, feel free to reopen it for review.
