### ISSUE TITLE
Write a guide for plugin developers

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#49]
## Context

[Over here](https://github.com/overhangio/2u-tutor-adoption/issues/29#issuecomment-1030135520) @regisb suggested making a step-by-step guide for new plugin developers.

Before doing this, we'll want to [settle on a V1 plugin interface](https://github.com/overhangio/2u-tutor-adoption/issues/32).

## Acceptance

Write a plugin developer guide containing:

* [ ] Introduction ("what is a plugin? why would I make one?")
* [ ] https://github.com/overhangio/2u-tutor-adoption/issues/33
* [ ] https://github.com/overhangio/2u-tutor-adoption/issues/29
* [ ] Tutorial of how to make a YAML plugin, by example
* [ ] Tutorial of how to make a Python plugin, by example
* [ ] https://github.com/overhangio/2u-tutor-adoption/issues/5
* [ ] A link to: https://github.com/overhangio/2u-tutor-adoption/issues/46
* [ ] ...Anything else?

This guide will (replace? extend? complement?) the existing [plugin development section in the docs](https://docs.tutor.overhang.io/plugins.html).

**Comment by kdmccormick** [comment]
@regisb What do you think?

**Comment by regisb** [comment]
I think that the bullet list is pretty comprehensive. I expect that there will not be a single plugin developer guide, but rather a series of tutorials which will be included in a new, dedicated "Plugin development" section of the [tutorial docs](https://docs.tutor.overhang.io/tutorials.html).

**Comment by kdmccormick** [comment]
Closing this issue in favor of an identical epic on the platform-roadmap: https://github.com/openedx/platform-roadmap/issues/123
