### ISSUE TITLE
Update cookiecutter-tutor-plugin to produce a V1 Plugin

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#57]
## Context

Once https://github.com/overhangio/2u-tutor-adoption/issues/32 is implemented, we should update https://github.com/overhangio/cookiecutter-tutor-plugin to produce a V1 Plugin instead of (or in addition to?) a V0 Plugin.

## Acceptance

TBD

**Comment by regisb** [comment]
Actually, all plugins should be migrated to the v1 API. I expect that this will be part of the work to migrate to Nutmeg.
