### ISSUE TITLE
Rewrite the tutor-mfe plugin to use the V1 API

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#59]
## Context

Once #32 is finished, we'll eventually need to rewrite the official plugins. It'll be good to have at least one plugin rewritten in time for the Lisbon conference. Let's try to do tutor-mfe, as there is a specific bugfix we could make to it once it's using the V1 API: https://discuss.overhang.io/t/why-is-the-mfe-image-not-pre-built/2260/6?u=kdmccormick

## Acceptance

Do it.

Integrate this hack into the rewrite: https://discuss.overhang.io/t/why-is-the-mfe-image-not-pre-built/2260/6?u=kdmccormick

**Comment by regisb** [comment]
Here's the PR: https://github.com/overhangio/tutor-mfe/pull/44

**Comment by kdmccormick** [comment]
was closed last week by https://github.com/overhangio/tutor-mfe/pull/44
