### ISSUE TITLE
`copyfrom` is not idempotent

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#76]
The first time you run `tutor ... copyfrom SVC SRC DST`, it'll copy `SRC` to `DST`.
The second time you run `tutor ... copyfrom SVC SRC DST`, it'll copy `SRC` to `DST/basename(SRC)`.

This behavior was entirely my idea (because it is similar to Unix's `cp` command) but after using the command several times, I'm having second thoughts :P

**Comment by regisb** [comment]
Wow I never realized that `cp` was not idempotent! The solution that is proposed in [this StackOverflow answer](https://unix.stackexchange.com/questions/228597/how-to-copy-a-folder-recursively-in-an-idempotent-way-using-cp#228637) is to run instead `cp -R inputFolder/. outputFolder`.

Despite the fact that the command is not idempotent, I still think that it's a good idea to emulate the behaviour of `cp`, which is intuitively understandable by most people. We should just be careful to include only idempotent commands in the documentation.

**Comment by kdmccormick** [comment]
> Despite the fact that the command is not idempotent, I still think that it's a good idea to emulate the behavior of cp, which is intuitively understandable by most people. 

Alright, I'll trust your judgement and stop doubting our original decision :)

> We should just be careful to include only idempotent commands in the documentation.

Agreed. I just checked out the [development docs](https://github.com/overhangio/tutor/blob/master/docs/dev.rst) and made sure that the example `copyfrom` command is idempotent.
