### ISSUE TITLE
Dissolve sub-projects in edx-platform & optimize Dockerfile

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#86]
## Context

See https://openedx.atlassian.net/browse/BOM-2579

In particular, note the optimization that BOM-2579 will unlock: https://openedx.atlassian.net/browse/BOM-2575?focusedCommentId=613181

More details and links to PRs can be seen here: https://discuss.openedx.org/t/breaking-apart-edx-platforms-common-lib-folder/7556

## Acceptance

* First, finish https://openedx.atlassian.net/browse/BOM-2579.
  *  Make sure https://github.com/overhangio/tutor/pull/719 merges, otherwise Tutor nightly build will break.
* Then, refactor [Tutor's edx-platform Dockerfile](https://github.com/overhangio/tutor/blob/nightly/tutor/templates/build/openedx/Dockerfile) so that changes to edx-platform code do not require re-installation of dependencies.
  * Done in https://github.com/overhangio/tutor/pull/728#event-7507800366

**Comment by kdmccormick** [comment]
Yes, definitely. The [final common/lib removal PR is in review right now](https://github.com/openedx/edx-platform/pull/30890). Once that merges, I can have a PR for the Tutor Dockerfile improvements ready shortly.

**Comment by regisb** [comment]
Awesome! This change should make it faster to rebuild the openedx Docker image.

**Comment by kdmccormick** [comment]
Completed by https://github.com/overhangio/tutor/pull/728
