### ISSUE TITLE
Deprecate `bindmount` and `--volume`

### ISSUE THREAD

**Issue by kdmccormick** [overhangio/2u-tutor-adoption#88]
## Context

* `--mount` was added in this PR: https://github.com/overhangio/tutor/pull/643 . This option replaces and improves `--volumes`.
* `copyfrom` was added in this PR: https://github.com/overhangio/tutor/pull/645 . This command replaces and improves `bindmount`.

We are ready to declare `--volumes` and `bindmount` as deprecated.

### code
Update the `bindmount` command description to mention that it is DEPRECATED and that the user should use `copyfrom` instead. Additionally, raise a deprecation warning whenever:
* `bindmount` is called
* `run`, `quickstart`, or `init` are called with `--volume(s)`

(Here's an example where we did the same thing for `runserver`: https://github.com/overhangio/tutor/pull/644/files#diff-ec320448cd20c7bd93a1b1d9bf8177f9ffb278cbbb071de216a0b45087386b52L100-R118)

### docs

Update the warnings for **Bind-mount from the “volumes/” directory** and **Manual bind-mount to any directory** to explicitly state their deprecation: https://docs.tutor.overhang.io/dev.html?highlight=dev#bind-mount-from-the-volumes-directory

Update any other Tutor docs references to `bindmount` and `--volumes` to use non-deprecated commands.

Search the `overhangio` GitHub organization for any remaining occurrences of `bindmount` (if there are any, it's probably in documentation). Replace them with equivalent `copyfrom` commands as appropriate.

**Comment by Carlos-Muniz** [comment]
Hey @kdmccormick I'll take this one on

**Comment by Carlos-Muniz** [comment]
Bindmount was deprecated in https://github.com/overhangio/tutor/commit/27449f4068186472c991ad50ff845d493504e25e?diff=split

**Comment by kdmccormick** [comment]
Bindmount stopped being a recommended workflow in https://github.com/overhangio/tutor/commit/27449f4068186472c991ad50ff845d493504e25e?diff=split, but it still has not been marked deprecated in the docs or in the CLI.

**Comment by kdmccormick** [comment]
Closed via https://github.com/overhangio/tutor/pull/736
